services:
  - type: web
    name: health-insurance-prediction
    env: python
    pythonVersion: 3.11.8
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
