[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#E8EBED"
textColor = "#000000"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "info"
